Feature/cop 2135 inject variable in form json
UKHomeOffice/cop-react-form-renderer pull request #126
Opened 2022-06-15 11:51 UTC by kam-cop

Functionality to interpolate following form json segments before processing them:

```
- pageOptions
- formComponents - excluding formComponents.data.url segment by copying over after interpolation

```

2022-06-15 15:03 UTC, paulfgraham requested changes

2022-06-15 16:54 UTC, kam-cop commented on src/utils/FormPage/getFormPage.js
> +    return formComponents.map((formComponent) => {
Thanks fixed extra indentation

2022-06-15 16:54 UTC, kam-cop commented on src/utils/FormPage/getFormPage.js
> +      let  interpolatedFormComponent = JSON.parse(Utils.interpolateString(JSON.stringify(formComponent), formData));
Thanks fixed it

2022-06-15 16:55 UTC, kam-cop commented on src/utils/FormPage/getFormPage.test.js
> +        { id: 'd', fieldId: 'd', label: 'Roger ${currentUser.firstname}', type: 'text' },
Fixed

2022-06-15 16:56 UTC, kam-cop commented on src/utils/FormPage/getFormPage.test.js
> +        { id: 'e', fieldId: 'e', label: 'Bravo ${currentUser.surname}', type: 'text' },
Fixed

2022-06-15 16:56 UTC, kam-cop commented on src/utils/FormPage/getFormPage.test.js
> +            { use: 'c', ...C, cya_label: C.label, full_path: C.fieldId, data: { url: '${urls.refData}/v3/charlies' } }
Fixed

2022-06-15 16:56 UTC, kam-cop commented on src/utils/FormPage/getFormPage.test.js
> +          title: 'Page ${postFixTitle}',
Fixed

2022-06-15 16:56 UTC, kam-cop commented on src/utils/FormPage/getFormPage.test.js
> +        const a = FORM_DATA;
Fixed

2022-06-15 17:13 UTC, paulfgraham requested changes
Just realised you need to change the version number in `package.json` or this can't be released and published to npm...

2022-06-16 08:24 UTC, paulfgraham requested changes

2022-06-16 08:24 UTC, paulfgraham commented on package.json
> +  "version": "3.0.2",
I don't know what this is playing at... but the version already in `main` is `"3.0.2"` so can you move this up to `"3.0.3"`, please, @kam-cop. 🙂

2022-06-16 08:30 UTC, merged