EAB-569 Added additional validation methods for minimum and maximum length
UKHomeOffice/cop-react-form-renderer pull request #153
Opened 2022-07-06 13:48 UTC by LewisClark-HO

2022-07-06 14:03 UTC, LewisClark-HO commented
Currently investigating why my git insists on saying the whole file has changed when changing a few lines...

2022-07-06 14:11 UTC, paulfgraham requested changes

2022-07-06 14:11 UTC, paulfgraham commented on src/utils/Validate/additional/index.js
> +  mustBeAfter, mustBeBefore,
Can you list these out fully vertically, rather than in a 2 x 3 grid?

2022-07-06 14:11 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.js
> + * @param {boolean} config.value - the value that string.length must be greater than.
The param is an `object` that contains a `boolean` value... so this is incorrectly commented.

2022-07-06 14:11 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeShorterThan.js
> + * @param {boolean} config.value - the value that string.length must be less than.
Again, the param is an `object` that contains a `boolean` value... so this is incorrectly commented.

2022-07-06 14:16 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.js
> +  return (string.length > config.value);
What about if `string` is `null` or `undefined`?

2022-07-06 14:17 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeShorterThan.js
> + * @param {boolean} config.value - the value that string.length must be less than.
What's the correct way to comment this - is it as `{object}` or as `{number}`? I'm not sure what's best.

2022-07-06 14:42 UTC, paulfgraham requested changes

2022-07-06 14:42 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.js
> +    return true;
`undefined.length > 3 === true`? 🤨

2022-07-06 14:42 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +        test('should return false given a string equal to the given length', () => {
There are no tests for when the text is `null` or `undefined`...

2022-07-06 14:42 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeShorterThan.test.js
> +        test('should return false given a string equal to the given length', () => {
There are no tests for when the text is `null` or `undefined`...

2022-07-12 12:14 UTC, paulfgraham requested changes

2022-07-12 12:14 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.js
> +    return true;
This remains unresolved and, actually, line 13 is plain wrong as it allows an empty string to be considered to have a length greater than specified:
`null.length > 3 === true`?
`''.length > 3 === true`?

2022-07-12 12:14 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
Yeah, why is this `true`? `''` is a string of length `0` (zero).

2022-07-12 12:14 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
And why does this differ from `undefined`? That doesn't make sense to me?

2022-07-12 12:14 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeShorterThan.js
> +  return (string.length < config.value);
Again, we have inconsistency here between the behaviour of `undefined`, `null`, and `''`.

I'd be inclined to always treat `undefined` and `null` the same as `''` in these methods - i.e., they should be considered to be strings of length zero.

You can either account for them directly, sort of as you're doing, or you can simply do something like this:
```
const str = string || '';
return str.length < config.value;
```

2022-07-12 12:28 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
My thinking was string being `null` would have to be intentional, so it should pass but `undefined` could be caused by an error. 

What you say below about treating both as an empty string makes perfect sense though - thank you!

2022-07-12 12:53 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
Given this, I would suggest both should look like this:
```
const mustBeLongerThan = (string, config) => {
  if (!string) {
    // null, undefined and empty strings should be picked up by the required flag
    // and not considered here as they would be valid for optional fields.
    return true;
  }
  return string.length > config.value; // And the reverse for mustBeShorterThan
};
```

I think it's important to explain why an empty string, which is _not_ longer than the length specified is considered valid and, equally, why it's treated exactly the same way on the shorter validation.

2022-07-12 12:55 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
I think they are aren't they? There doesn't need to be an explicit catch for that in `mustBeShorterThan` because they will all pass by default unless someone sets value as something silly, i.e. <= 0.

2022-07-12 12:56 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
Yeah, good point! Will add the comments.

2022-07-12 12:59 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeLongerThan.test.js
> +          expect(result).toEqual(true);
> I think they are aren't they? There doesn't need to be an explicit catch for that in `mustBeShorterThan` because they will all pass by default unless someone sets value as something silly, i.e. <= 0.

Yes, they would all pass with your current implementation, but calling it out as being specifically ignored and considered valid is really useful from a code maintenance point of view. 🙂

2022-07-12 13:45 UTC, merged