Added support for "contains" operator on conditional display
UKHomeOffice/cop-react-form-renderer pull request #164
Opened 2022-07-15 15:21 UTC by georgepemberton1998

### Description
show_when can now be passed on a component or page with the `contains` operator. This is different to the `in` operator in that the in operator is used to pass an array of accepted values that a given field is "in", whereas `contains` is used to pass a single accepted value which is "in" a field.

### To test
Covered by accompanying unit tests. Functionality can be tested in the Form Renderer Sandbox by adding a component with a show_when with "op": "contains".
1. Add an array field to the `initial data` tab in form renderer sandbox. e.g. "something" : ["alpha", "bravo", "charlie" ]
2. use the below component and confirm that it is displayed
```
    {
      "id": "status",
      "fieldId": "status",
      "type": "text",
      "label": "select status",
      "required": true,
      "show_when": [
        {
          "field": "something",
          "op": "contains",
          "value": "alpha"
        }
      ]
    }
```
3. change the component check for a value not in the array and confirm that it is no longer displayed
```
    {
      "id": "status",
      "fieldId": "status",
      "type": "text",
      "label": "select status",
      "required": true,
      "show_when": [
        {
          "field": "something",
          "op": "contains",
          "value": "delta"
        }
      ]
    }
```

2022-07-15 15:22 UTC, georgepemberton1998 commented
Converting to a draft until PR #163 has been merged

2022-07-20 10:54 UTC, paulfgraham requested changes

2022-07-20 10:54 UTC, paulfgraham commented on src/utils/Condition/meetsCondition.js
> +        return value.toString().includes(compare);
If `value` is `null` or `undefined`, this will fail. It's also case-sensitive, which _may_ be the desired behaviour but may actually just be something that hasn't been considered. If the former, can we have a note expressing why case sensitivity is important.

2022-07-20 10:54 UTC, paulfgraham commented on src/docs/ConditionalDisplayExamples.stories.mdx
> +An array containing `BMW` e.g. `"cars": "['Ford', 'Mercedes', 'BMW', 'Lexus']"` <br/>
You don't need this for arrays unless you want to consider sub-strings of the items in arrays. For arrays, `op: 'in'` does that job.

Also, in your example, `cars` is _not_ an array, it's a string representation of an array.

2022-07-20 10:54 UTC, paulfgraham commented on src/utils/Condition/meetsCondition.test.js
> +
As mentioned in a previous comment, you need tests for `null` and `undefined` values.

2022-07-20 11:31 UTC, georgepemberton1998 commented on src/docs/ConditionalDisplayExamples.stories.mdx
> +An array containing `BMW` e.g. `"cars": "['Ford', 'Mercedes', 'BMW', 'Lexus']"` <br/>
My understand with `op: 'in'` is that it can be used to provide an `array value` and check if a `field` is "in" that array value. The `contains` operator would essentially do the opposite of this. You can provide a `field array` and check if a given value is in that. I looked at uplifting the "in" operator to enable this functionality but I believed it to be quite confusing.

To clarify - as part of the context data we have an array field "groups" (below) - I would like to display a component if `"/bf-intel"` is in the `groups` array. I was unable to see a way to use this with the "in" operator without a code change to it. Please let me know if I have missed something.

```
"shiftDetailsContext": {
    [
     ---
    "groups" [
      "/bf-intel",
      "/bfrole",
      "/camunda-admin"
    ]
    ---
    ]
}
```

2022-07-20 11:34 UTC, paulfgraham commented on src/docs/ConditionalDisplayExamples.stories.mdx
> +An array containing `BMW` e.g. `"cars": "['Ford', 'Mercedes', 'BMW', 'Lexus']"` <br/>
Ah, I see what you mean. Yes, you're absolutely right!

The point about it being a string representation of an array remains, though. 🙂

2022-07-20 12:17 UTC, paulfgraham requested changes

2022-07-20 12:17 UTC, paulfgraham commented on src/utils/Condition/meetsCondition.js
> +        if (value){
```suggestion
        if (value) {
```

Alternatively, this whole thing could simply be:
```
        return value?.toString().includes(compare);
```

2022-07-20 12:17 UTC, paulfgraham commented on src/utils/Condition/meetsCondition.js
> +       // If no value is provided, the field cannot contain it, so it must fail the condition.
The indenting on this line and the one below is off - it's a single space too far back.

2022-07-20 12:17 UTC, paulfgraham commented on src/utils/Condition/meetsCondition.test.js
> +    it('should reject any value when the field is undefined', () => {
```suggestion
    it('should reject any value when the field is null', () => {
```

2022-07-20 13:26 UTC, merged