Feature/EAB-794 Implement partial collections
UKHomeOffice/cop-react-form-renderer pull request #183
Opened 2022-08-10 14:22 UTC by LewisClark-HO

### Description
This PR adds Partial Collections - collections of components that can be split across multiple pages. There will be a few more PRs relating to Partial Collections in order to get them in a usable state.

This PR deals with the following parts of Partial Collections:
- How they are defined in a form renderer JSON file.
- How they are validated.
- How the Partial Collection's data is structured in `formData`. This is identical to how regular Collections do it to allow swapping between the two in the future.

Future PRs will be needed to deal with:
- Displaying the Partial Collection on a CYA screen.
- Allowing the User to add/remove/change entries.
- Navigating back to the start/first page of a Partial Collection.

### Example
Below is an example definition of two Partial Collection components.
```
...
    {
      "id": "peopleNames",
      "fieldId": "peopleNames",
      "type": "partial-collection",
      "collectionName": "people",
      "item": [
        {
          "id": "firstName",
          "fieldId": "firstName",
          "label": "First name",
          "type": "text",
          "required": true
        },
        {
          "id": "surname",
          "fieldId": "surname",
          "label": "Surname",
          "type": "text",
          "required": true
        }
      ]
    },
    {
      "id": "peopleDateOfBirth",
      "fieldId": "peopleDateOfBirth",
      "type": "partial-collection",
      "collectionName": "people",
      "item": [
        {
          "id": "dateOfBirth",
          "fieldId": "dateOfBirth",
          "label": "Date of birth",
          "type": "date",
          "required": true
        }
      ]
    }
...
```
`collectionName` determines where the Partial Collection's data is stored in `formData`. Any Partial Collections that have the same `collectionName` will lump their data in together. 

Given a form with two pages, each containing one of the components defined above, the final data for the Partial Collections would look something like:

```
"people": [
  {
    "firstName": "Joe",
    "surname": "Bloggs",
    "dateOfBirth": "01-01-2000"
  }
]
```
### Testing
Unit tests will be added before PR is 'ready for review'.

2022-08-11 15:21 UTC, paulfgraham requested changes

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import getCYARowsForPartialCollection from './getCYARowsForPartialCollection';
This one isn't alphabetical.

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +        case ComponentTypes.COLLECTION:
There appears to be an extraneous space on the end of this line. I'm surprised lint hasn't picked up on this.

2022-08-11 15:21 UTC, paulfgraham commented on src/components/FormComponent/FormComponent.jsx
> +import PartialCollection from './PartialCollection';
This hasn't been imported alphabetically.

2022-08-11 15:21 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.jsx
> +  value: _value,
You don't appear to be using this within the component...?

2022-08-11 15:21 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.jsx
> +  value: PropTypes.arrayOf(PropTypes.shape()),
Again, this isn't actually being used...

2022-08-11 15:21 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.jsx
> +  value: []
Nor this.

2022-08-11 15:21 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.scss
> +.hods-form-partial-collection {
Apart from the class name, this is identical to `Collection.scss`.

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPartialCollection.js
> +      label: "Change",
Single quotes rather than double quotes. And, again, everything in here looks essentially identical to `getCYARowsForCollection.js`. Can you reuse some of those instead of duplicating the code?

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/Component/getDefaultValue.test.js
> -import { ComponentTypes } from '../../models';
What's happened in here? How come all of the lines are showing as changed even though they don't look like they have?

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/Component/getDefaultValue.test.js
> +    if (![ComponentTypes.COLLECTION, ComponentTypes.CONTAINER, ComponentTypes.FILE].includes(value)) {
Is this not failing for partial collections? It looks like it should... and if it's _not_, maybe the test isn't working properly. 🤔

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/PartialCollection/getPartialCollectionActiveId.test.js
> +    describe('getPartialCollectionActiveId', () => {
This nesting thing got a bit out of hand somewhere along the line... can we start going with dot notation on a single `describe` line at the top?

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/PartialCollection/getPartialCollectionActiveIndex.test.js
> +    describe('getPartialCollectionActiveIndex', () => {
The same comment about this nesting of `describe` blocks.

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/Validate/validateComponent.test.js
> -// Local imports
Why have all the lines also apparently changed in here?

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/Validate/validateComponent.test.js
> +});
Not something to do in this PR necessarily, but this file is getting too big now - it would be better if it was split up into a series of test files, I think.

2022-08-11 15:21 UTC, paulfgraham commented on src/utils/Validate/validatePartialCollection.js
> +import Utils from "..";
This sets up a circular dependency. I think you ought to be doing this instead:
```suggestion
import PartialCollection from '../PartialCollection';
```

And then adjusting line 14 accordingly.

2022-08-11 15:50 UTC, LewisClark-HO commented on src/utils/CheckYourAnswers/getCYARowsForPartialCollection.js
> +      label: "Change",
It is almost an identical copy. I've done it this way just to get _something_ displaying on the CYA screen for now. This will be changed significantly with coming PRs - and before the feature branch gets merged into main :)

2022-08-11 16:00 UTC, LewisClark-HO commented on src/components/FormComponent/PartialCollection.scss
> +.hods-form-partial-collection {
Is it best to just keep the `DEFAULT_CLASS` for Partial Collections the same as it is for Collections and reuse the `.scss` file?

2022-08-12 08:21 UTC, paulfgraham commented on src/components/FormComponent/FormComponent.jsx
> +import Utils from '../../utils';
Ha. I see what you did there. It's not _quite_ pure alphabetical order. It also follows the directory structure so anything where you have to go `../../zebra` should appear higher up than anything where you go `./antelope`.

If you're using VS Code, you can use "Organise imports" from the Command Palette (under the View menu). On my Mac, it's Option + Shift + O (the letter "O", not zero) but the Command Palette should tell you what the shortcut is on your machine if it's not that.

2022-08-12 08:25 UTC, LewisClark-HO commented on src/components/FormComponent/FormComponent.jsx
> +import Utils from '../../utils';
Ah ok! My bad, thanks for the tip 😅

2022-08-12 08:27 UTC, paulfgraham approved these changes
There are some import ordering issues and a missing semicolon... but I don't think those are blockers; just things to ideally address.

I'll approve it now, regardless of whether those get sorted before merging.

2022-08-12 08:27 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.jsx
> +  }
Just realised this is missing a semicolon.

2022-08-12 08:27 UTC, paulfgraham commented on src/components/FormComponent/PartialCollection.test.js
> +import FormComponent from './FormComponent';
Again, we've got imports not organised quite right. Not a blocker for the PR... but something to work on getting right, I think, or else you end up with PRs changing imports and (potentially) a tug-of-war over the order.

2022-08-12 08:27 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import getCYARowForGroup from './getCYARowForGroup';
This one shouldn't have moved as it's `RowF` rather than `RowsF` - "F" comes before "s".

2022-08-12 08:27 UTC, paulfgraham commented on src/utils/Validate/validatePartialCollection.js
> +import PartialCollection from '../PartialCollection';
The same thing about ordering here.

2022-08-12 08:31 UTC, paulfgraham commented on src/components/FormComponent/FormComponent.jsx
> +import Utils from '../../utils';
And if you're not using VS Code, maybe give it a go. Whatever IDE you _are_ using should probably have an equivalent.

If we find they disagree, it might be sensible to add `prettier` to the dependencies and make that a pre-commit hook.

2022-08-12 08:47 UTC, merged