Added additional validation for quantity fields
UKHomeOffice/cop-react-form-renderer pull request #234
Opened 2022-09-21 14:48 UTC by Deepak-Bagrawat

Additional validation requires for quantity fields in record items details page.
https://support.cop.homeoffice.gov.uk/browse/EAB-1014

2022-09-21 14:54 UTC, gardnersam commented on src/utils/Validate/additional/mustBeEqualToOrLessThan.test.js
> +          console.log(result);
some debug remains

2022-09-21 14:54 UTC, gardnersam commented on src/utils/Validate/additional/mustBeNumbersOnly.test.js
> +          const result = mustBeNumbersOnly(null, {value: 3});
the last three tests put two arguments in but the function only takes one

2022-09-21 14:55 UTC, LewisClark-HO requested changes

2022-09-21 14:55 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeNumbersOnly.js
> +  export default mustBeNumbersOnly;
This file and `mustBeEqualToOrLessThan.js` are missing newlines at the end.

2022-09-21 14:55 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeEqualToOrLessThan.js
> + const mustBeEqualToOrLessThan = (string, config) => {
Just personal opinion, but I think it would be more concise to rename this function & file to `mustBeLessThan`. Then it's in keeping with the other validation checks.

2022-09-21 14:56 UTC, gardnersam commented on src/utils/Validate/additional/index.js
> +import mustBeNumbersOnly  from './mustBeNumbersOnly';
we should put these in the Component.stories.mdx under additionalValidation

2022-09-21 15:58 UTC, Deepak-Bagrawat commented on src/utils/Validate/additional/mustBeEqualToOrLessThan.test.js
> +          console.log(result);
Removed

2022-09-21 15:58 UTC, Deepak-Bagrawat commented on src/utils/Validate/additional/mustBeNumbersOnly.test.js
> +          const result = mustBeNumbersOnly(null, {value: 3});
Removed extra arguments

2022-09-21 15:59 UTC, Deepak-Bagrawat commented on src/utils/Validate/additional/mustBeNumbersOnly.js
> +  export default mustBeNumbersOnly;
Added extra line

2022-09-21 16:13 UTC, Deepak-Bagrawat commented on src/utils/Validate/additional/index.js
> +import mustBeNumbersOnly  from './mustBeNumbersOnly';
Added these in Component.stories.mdx

2022-09-22 10:40 UTC, LewisClark-HO approved these changes
LGTM, just some general changes that would make the code a little more readable.

2022-09-22 10:40 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeNumbersOnly.test.js
> +      describe('mustBeNumbersOnly', () => {
I think it would be cleaner to put all these describes in one - that's the way it's done in other files where there starts to be a lot of levels like this. So you'd change it to: `describe('utils.Validate.additional.mustBeNumbersOnly, () =>`

2022-09-22 10:40 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeLessThan.test.js
> +      describe('mustBeShorterThan', () => {
Same comment as below, would avoid nesting if these were all put in one `describe`.

2022-09-22 10:40 UTC, LewisClark-HO commented on src/utils/Validate/additional/mustBeNumbersOnly.js
> +
Not sure why this is still moaning about missing new lines...

2022-09-22 10:48 UTC, merged