EAB-174 Add date validation capabilityo DateInput
UKHomeOffice/cop-react-form-renderer pull request #65
Opened 2022-03-28 12:51 UTC by gardnersam

2022-03-28 14:20 UTC, paulfgraham requested changes
A couple of specific points, but we've discussed some refactoring separately.

2022-03-28 14:20 UTC, paulfgraham commented on src/utils/Validate/validateDate.js
> +  if (day > 31 || day < 1) {
What if it's February, April, June, September, or November? I can see that 30/02/2022 would get handled in line 43... but 32/02/2022 would get caught right here and saying "Must be between 1 and 31" is wrong for February. 🙂

2022-03-30 08:57 UTC, paulfgraham reviewed
A few questions and comments.

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeAfter.test.js
> +test('should return true given a date after the given number of months in the future', () => {
We usually wrap all the tests within a file within a `describe(...)` block:

`describe('utils.Validate.additional.mustBeAfter', () => {`

And similar for the other test files...

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeBefore.js
> + * @param {*} dateToCheck - date string in a valid date format e.g. DD-MM-YYYY
```suggestion
 * @param {string} dateToCheck - date string in a valid date format e.g. DD-MM-YYYY
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeBefore.js
> + * @param {*} config.unit - day, month or year
```suggestion
 * @param {string} config.unit - day, month or year
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeBefore.js
> + * @param {*} config.value - number of the unit to be before
```suggestion
 * @param {number} config.value - number of the unit to be before
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInTheFuture.js
> + * @param {*} date - date string e.g. '03-12-2021'
```suggestion
 * @param {string} date - date string e.g. '03-12-2021'
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInTheFuture.js
> + * @param {*} config.todayAllowed - true if today should be a valid date
```suggestion
 * @param {boolean} config.todayAllowed - true if today should be a valid date
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInThePast.js
> + * @param {*} date - date string e.g. '03-12-2021'
```suggestion
 * @param {string} date - date string e.g. '03-12-2021'
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInThePast.js
> + * @param {*} config.todayAllowed - true if today should be a valid date
```suggestion
 * @param {boolean} config.todayAllowed - true if today should be a valid date
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustbeAfter.js
> + * @param {*} date - date string in a valid date format e.g. DD-MM-YYYY
```suggestion
 * @param {string} date - date string in a valid date format e.g. DD-MM-YYYY
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustbeAfter.js
> + * @param {*} config.unit - day, month or year
```suggestion
 * @param {string} config.unit - day, month or year
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/mustbeAfter.js
> + * @param {*} config.value - number of the unit to be after
```suggestion
 * @param {number} config.value - number of the unit to be after
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/additional/utils.js
> +  let result = '';
This would be an easier implementation:
```
if (isNumeric(dateComponent)) {
  return dateComponent.padStart(2, '0');
}
return '';
```

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/validateComponent.js
> +      component.propsinerror = propsinerror;
I'm not seeing this being cleared out anywhere in this method. And I'm unsure how this behaves if it fails the `required` validation - it _looks_ like it'll show no red borders on the fields if it fails it initially but then show whatever was in place if it fails a different validation and then is cleared out again.

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/validateComponent.test.js
> +        // it('should apply optional validators when specified', () => {
Why are these commented out? If they're not needed, can you delete them? 🙂

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/validateDate.js
> +  if (day > maxDays || day < 1) {
I'm slightly confused by this now because it looks like `day`, `month`, and `year` are strings... but you're treating `day` like a number on this line and the same for `month` on line 47. It _works_ because JavaScript is forgiving... but it would be better to compare a number with a number.

2022-03-30 08:57 UTC, paulfgraham commented on src/utils/Validate/validateDate.js
> +  if (month > 12 || month < 1) {
`string > number || string < number`

2022-03-30 11:09 UTC, gardnersam commented on src/utils/Validate/additional/mustBeAfter.test.js
> +test('should return true given a date after the given number of months in the future', () => {
I've wrapped them all up matching the format of the other tests now

2022-03-30 11:09 UTC, gardnersam commented on src/utils/Validate/additional/utils.js
> +  let result = '';
Agreed, I've swapped to this

2022-03-30 11:09 UTC, gardnersam commented on src/utils/Validate/validateComponent.js
> +      component.propsinerror = propsinerror;
Added a clear at the start as discussed

2022-03-30 11:10 UTC, gardnersam commented on src/utils/Validate/validateComponent.test.js
> +        // it('should apply optional validators when specified', () => {
My bad, kept one and deleted the other

2022-03-30 11:10 UTC, gardnersam commented on src/utils/Validate/validateDate.js
> +  if (day > maxDays || day < 1) {
Parsed the strings into ints for these comparisons

2022-03-30 11:17 UTC, paulfgraham requested changes
Just a couple of small things to improve the code efficiency. Otherwise, it's looking good...

2022-03-30 11:17 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInTheFuture.js
> +  return dayjs(formatString(date), DATE_FORMAT).isToday() && !!config?.todayAllowed;
Hmmm... I'd swap these around as I think `!!config?.todayAllowed` is a less expensive operation than formatting the date and finding out of it's today... but that's just a nitpick. I think the same will be true in `mustBeInThePast` too.

2022-03-30 11:17 UTC, paulfgraham commented on src/utils/Validate/additional/mustBeInThePast.js
> +  const isToday = dayjs(formatString(date), DATE_FORMAT).isToday();
Ah, this doesn't need to be done here as you'll drop out early if it's _before_ today guaranteed. This should mirror the `mustBeInTheFuture` function.

2022-03-30 11:33 UTC, gardnersam commented on src/utils/Validate/additional/mustBeInTheFuture.js
> +  return dayjs(formatString(date), DATE_FORMAT).isToday() && !!config?.todayAllowed;
Good shout, I've swapped them. `mustBeInThePast` is already comparing two booleans so no worries there.

2022-03-30 11:34 UTC, gardnersam commented on src/utils/Validate/additional/mustBeInThePast.js
> +  const isToday = dayjs(formatString(date), DATE_FORMAT).isToday();
Discussed on Slack and added a comment instead

2022-03-30 12:27 UTC, paulfgraham approved these changes
Thanks for making the requested changes and answering my other questions, @gardnersam. Approved. 👍

2022-04-28 13:37 UTC, merged