Feature/cop 10344/caseview v3
UKHomeOffice/cop-react-form-renderer pull request #67
Opened 2022-04-04 11:07 UTC by keenan218

### Description
This change has been done to support changes in cop to display read-only versions of submitted forms when in CaseView. The styling has been applied to match what was outlined in the figma documentation containing the initial designs of CaseView.

https://support.cop.homeoffice.gov.uk/browse/COP-10344

### To test
Testing that the functionality works can be achieved by viewing the changes in storybook (`yarn storybook`) and looking in each of the respected sections for Check Your Answers, Form Renderer and Summary List. At the bottom there will be a read-only view which contains no change actions, or no lines.

2022-04-05 09:24 UTC, gardnersam requested changes
Looks good overall, few thoughts on some of the implementation details

2022-04-05 09:24 UTC, gardnersam commented on src/components/CheckYourAnswers/CheckYourAnswers.test.js
> +      const title = cya.childNodes[0];
I don't think this is / should be the title, it looks like it should be the output from the pages.map() starting on line 78.

2022-04-05 09:24 UTC, gardnersam commented on src/components/CheckYourAnswers/CheckYourAnswers.jsx
> +  noAction,
This and invertWeight are purely here to be passed on to the summary list so wonder if that could be in the name like 'summaryListClassModifiers'. Not a deal breaker but I think it's confusing having hide_actions and noAction

2022-04-05 09:24 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +  summaryListClassModifiers: PropTypes.string,
same comment as above, should have an array allowed here

2022-04-05 09:24 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +  summaryListClassModifiers: null,
would be more consistent to default this to [] like classModifiers

2022-04-05 09:24 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +        invertWeight ? (
I don't really understand what invertWeight is supposed to do, but the only difference in the code seems to be adding the two styles `caseview__key` and `caseview__value`. So could the code duplication be reduced by determining the classes upfront ie `const keyStyle = invertWeight ? 'key caseview__key' : 'key'` then have a single block of code which takes `keyStyle` and a simular `valueStyle` for the input to classes like `<dt className={classes(keyStyle)}>{row.key}</dt>`

2022-04-05 09:24 UTC, gardnersam commented on src/components/SummaryList/SummaryList.scss
> +.caseview__key {
now i've got down here it seems like the `invertWeight` prop on SummaryList is to adjust the font weight so maybe could be named clearer to reflect that

2022-04-05 09:24 UTC, gardnersam commented on src/components/SummaryList/SummaryList.test.js
> +    const checkRowNoActions = (summaryList, index) => {
this function doesn't check that there are no actions, if anything it seems to assume there are actions and return them

2022-04-05 09:24 UTC, gardnersam commented on src/components/SummaryList/SummaryList.test.js
> +        expect(valueDiv.textContent).toEqual(VALUES[index]);
There doesn't seem to be a check that actions are hidden, could we check that the length of the childNodes array for the row is 2? (if that's the right answer)

2022-04-05 10:14 UTC, keenan218 commented on package.json
> +  "version": "2.0.1",
Understood, will change thanks

2022-04-05 10:16 UTC, keenan218 commented on src/components/CheckYourAnswers/CheckYourAnswers.jsx
> +  noAction,
Point taken, could be confusing having both pretty similar, will look into this

2022-04-05 11:33 UTC, keenan218 commented on src/components/CheckYourAnswers/CheckYourAnswers.jsx
> +  summaryListClassModifiers: PropTypes.string,
Will change this to reflect how the PropTypes are in SummaryList

2022-04-05 13:30 UTC, keenan218 commented on src/components/FormRenderer/FormRenderer.jsx
> +  summaryListClassModifiers: null,
Yep i agree, will get that changed

2022-04-05 14:34 UTC, keenan218 commented on src/components/SummaryList/SummaryList.scss
> +.caseview__key {
invertWeight has been changed to invertFontWeight, used when swapping a bold font to normal font, hope this is better.

2022-04-05 14:45 UTC, keenan218 commented on src/components/SummaryList/SummaryList.scss
> +.caseview__key {
After re-checking the figma it has changed once more and now it seems the invertWeight functionality is now not needed..

2022-04-06 08:40 UTC, keenan218 commented on src/components/CheckYourAnswers/CheckYourAnswers.test.js
> +      const title = cya.childNodes[0];
A more suitable name has been given to this rather than title

2022-04-06 08:42 UTC, keenan218 commented on src/components/CheckYourAnswers/CheckYourAnswers.jsx
> +  noAction,
I have given noAction a more suitable name of noChangeAction so it hopefully doesn't clash with hide_actions too much

2022-04-06 09:03 UTC, keenan218 commented on src/components/SummaryList/SummaryList.test.js
> +        expect(valueDiv.textContent).toEqual(VALUES[index]);
We have now included a check for the length of the childNodes array being only 2

2022-04-06 09:06 UTC, keenan218 commented on src/components/SummaryList/SummaryList.test.js
> +    const checkRowNoActions = (summaryList, index) => {
Have altered the function so it checks that there are no actions and does not return any actions.

2022-04-06 10:09 UTC, gardnersam approved these changes
Looks good!

2022-04-06 10:11 UTC, merged