COP-10034 Add basic non functional Task List component
UKHomeOffice/cop-react-form-renderer pull request #68
Opened 2022-04-06 10:35 UTC by gardnersam

### Summary
Adds the Task List component. At this point the TaskList is largely non functional and simply displays the correct things in the correct way with the ability to update state and link status. 

Styling is a bit loose as decisions around what the status tags should look like are not finalised. An effort has been made to match the figma designs roughly - blue things are blue - but as the exact shade of blue is up for discussion still will have to be returned to later. 

The file `TaskList.scss` has been taken from here [task-list.scss](https://github.com/alphagov/govuk-prototype-kit/blob/main/app/assets/sass/patterns/_task-list.scss) with the assumption that this will be finalised and included in the `govuk-frontend` styling package at some point in the future. 

TODOs have been left where future work is covered by tickets, this includes the ability to determine the status for each task properly and to launch into the relevant pages for each task. 

### Testing
A storybook page has been added to the form-renderer storybook for the TaskList so this is the easiest way to view one rendered. It can also be viewed using the sandbox. Unit test coverage is 100% for the added files.

2022-04-06 14:10 UTC, paulfgraham commented on package.json
> +  "version": "2.2.0",
Since this is an incomplete feature, it should go down as a pre-release version until such time as it is complete.
```suggestion
  "version": "2.2.0-alpha",
```

2022-04-06 14:11 UTC, paulfgraham commented on src/components/TaskList/Task.jsx
> +export const DEFAULT_CLASS = 'app-task-list';
_Suggestion:_
```suggestion
export const DEFAULT_CLASS = 'hods-task-list';
```

2022-04-06 14:12 UTC, paulfgraham commented on src/components/TaskList/TaskList.scss
> +// Task list pattern
The indenting in here is off.

2022-04-06 14:13 UTC, paulfgraham commented on src/components/TaskList/TaskList.test.js
> +  describe('TaskList.TaskList', () => {
```suggestion
  describe('TaskList', () => {
```

2022-04-06 14:17 UTC, paulfgraham commented on src/utils/Component/getComponent.js
> +    case ComponentTypes.TASKLIST:
Errr... why is it being used in this way? Are you expecting to have a component defined in the JSON that is of type `"tasklist"`? Surely this is simply a mode of the form renderer, isn't it?

2022-04-06 14:18 UTC, paulfgraham requested changes
Added some inline comments. Based on the description, this should be a pre-release so the version should reflect that. Also, I'm confused about the appearance of the `TaskList` in the `getComponent` utility method - that isn't how I imagined it would be used.

2022-04-07 12:31 UTC, gardnersam commented on src/components/TaskList/TaskList.scss
> +// Task list pattern
Good spot, reformatted

2022-04-07 12:32 UTC, gardnersam commented on src/components/TaskList/TaskState.jsx
> +  const [currentState, setCurrentState] = useState(state);
Fair point, I'd forgotten somehow that the form will rerender on a prop update so have removed the useState()

2022-04-07 13:11 UTC, paulfgraham commented on src/components/TaskList/TaskState.test.js
> +      expect(container.childNodes[0].textContent).toEqual('Completed');
In addition, you can expect these values to equal the ones from the appropriate entry, rather than checking for hard-coded strings.

2022-04-07 13:12 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +const TaskList = ({ copRefNum, sections, fieldId, onTaskAction, classBlock, classModifiers, className, ...attrs }) => {
`copRefNum` is not at all generic. Given how it's being used, can you simply call it `title`?

2022-04-07 13:13 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +      <h2 className='govuk-heading-s govuk-!-margin-bottom-2'>{`COP reference number ${copRefNum}`}</h2>
And if it comes through as `title`, can the title _include_ ``COP reference number``, rather than hard-coding it here?

2022-04-07 13:17 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +      totalComplete +
I think this is easier:
```suggestion
      totalComplete + currentSection.tasks.filter(t => t.state === 'complete').length;
```

2022-04-07 13:18 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +    if(typeof onTaskAction === 'function'){
```suggestion
    if (typeof onTaskAction === 'function') {
```

2022-04-07 13:20 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +          <Fragment key={`${section.title}-${index}`}>
You should avoid using an index as a `key` as it can cause performance issues. In this particular instance, it probably doesn't matter hugely but some linters will definitely fail this. I think `section.title` is actually completely fine as a `key` in this instance as they're (almost certainly) unique within a given form.

2022-04-07 13:25 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +  sections: PropTypes.array,
Can you specify what this is an array of?

2022-04-07 13:30 UTC, paulfgraham commented on src/components/TaskList/TaskList.test.js
> +            { taskName: 'Nice task', state: 'complete' },
None of the tasks in these tests include a `firstPage` property... 🤔

2022-04-11 11:21 UTC, gardnersam commented on src/utils/Hub/getFormHub.js
> +  if(type === FormTypes.TASK && hub){
Agreed, hub removed

2022-04-11 11:21 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +import TaskList from '../TaskList';
Updated

2022-04-11 11:23 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +      {hub === 'TASK' && <TaskList sections={_hub.sections} copRefNum={_hub.copRefNum} onTaskAction={onTaskAction}/>}
I've added documentation to the Form storybook page.

Following from our conversation this morning I've taken the `businessKey` from the `data` prop as this seems to be the part of the JSON that COP UI populates it with. I've updated the default data for the sandbox to include a business key also.

2022-04-11 11:23 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +      {hub === 'TASK' && <TaskList sections={_hub.sections} copRefNum={_hub.copRefNum} onTaskAction={onTaskAction}/>}
Yep updated

2022-04-11 11:23 UTC, gardnersam commented on src/components/FormRenderer/FormRenderer.jsx
> +  type: PropTypes.oneOf([FormTypes.CYA, FormTypes.FORM, FormTypes.HUB, FormTypes.WIZARD, FormTypes.TASK]).isRequired,
Updated

2022-04-11 11:23 UTC, gardnersam commented on src/components/TaskList/Task.jsx
> +  task: PropTypes.object,
Good idea, swapped to name

2022-04-11 11:23 UTC, gardnersam commented on src/models/FormTypes.js
> +const TYPE_TASK_LIST = 'task-list';
Updated

2022-04-11 11:23 UTC, gardnersam commented on src/models/FormTypes.js
> +  TASK: TYPE_TASK_LIST,
Updated

2022-04-11 11:23 UTC, gardnersam commented on src/components/TaskList/index.js
> +import TaskList from "./TaskList";
Updated

2022-04-11 11:24 UTC, gardnersam commented on src/components/TaskList/TaskState.jsx
> +  const STATE_OPTIONS = {
Moved to models, definitely a cleaner solution

2022-04-11 11:24 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +const TaskList = ({ copRefNum, sections, fieldId, onTaskAction, classBlock, classModifiers, className, ...attrs }) => {
Now using refTitle and refNumber as discussed

2022-04-11 11:25 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +      totalComplete +
Nice, updated

2022-04-11 11:25 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +    if(typeof onTaskAction === 'function'){
Update

2022-04-11 11:25 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +          <Fragment key={`${section.title}-${index}`}>
Thanks, good to know, i've fixed this now

2022-04-11 11:26 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +                <Task key={`task-${taskIndex}`} task={task} state={task.state} onClick={onClick} />
Updated the key and and now using the `state` that is passed in with `task`, I'd initially passed them separatly as I was thinking `state` was going to come from elsewhere in the future but there's no reason it wouldn't be attached to the `task` object later on anyway

2022-04-11 11:27 UTC, gardnersam commented on src/components/TaskList/TaskList.jsx
> +  sections: PropTypes.array,
Yep, updated

2022-04-11 11:27 UTC, gardnersam commented on src/components/TaskList/TaskList.scss
> +.hods-task-list__section {
I've done this, I'm no scss expert so hopefully it's correct, it works and I'm 95% sure the formatting is correct

2022-04-11 11:27 UTC, gardnersam commented on src/components/TaskList/TaskList.test.js
> +            { taskName: 'Nice task', state: 'complete' },
Updated to include the property and added a test to check that the `firstPage` value is given back when it should be

2022-04-11 15:17 UTC, paulfgraham requested changes

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/Task.jsx
> +    setLinkActive(task.state !== 'cannotStartYet');
```suggestion
    setLinkActive(task.state !== TaskStates.TYPES.CANNOT_START_YET);
```

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/Task.jsx
> +  onClick: PropTypes.func,
```suggestion
  onClick: PropTypes.func.isRequired,
```

Either this needs to be a required parameter or it being `null` or `undefined` needs to be handled appropriately.

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/Task.test.js
> +      const STATE = 'cannotStartYet';
```suggestion
      const STATE = TaskStates.TYPES.CANNOT_START_YET;
```

And the same for all the other hard-coded instances in here. 😁

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +  ),
Surely this is required...? And maybe some of the properties within the shape...?

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/TaskList.jsx
> +  fieldId: PropTypes.string,
It doesn't look like `fieldId` is being used within this component.

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/TaskList.scss
> +.hods-task-list__section {
Not seeing the nesting in here... but this isn't a blocker anyway. I'm happy to go through it with you at some point. 🙂

2022-04-11 15:17 UTC, paulfgraham commented on src/components/TaskList/Task.jsx
> +  }, [task]);
```suggestion
  }, [task, setLinkActive, setCurrentState]);
```

2022-04-11 16:16 UTC, gardnersam commented on src/components/TaskList/TaskState.test.js
> +  });
Added tests to cover these

2022-04-19 14:11 UTC, paulfgraham approved these changes
Thank you for making the requested changes, @gardnersam. This looks good. 👍

2022-04-28 11:02 UTC, merged