Add ability to display answers from multiple fields in a single row
UKHomeOffice/cop-react-form-renderer pull request #88
Opened 2022-05-16 07:57 UTC by Deepak-Bagrawat

2022-05-16 08:16 UTC, paulfgraham requested changes

2022-05-16 08:16 UTC, paulfgraham commented on src/components/SummaryList/SummaryList.scss
> +}
Needs a carriage return at the end here - GitHub's showing a warning for this.

2022-05-16 08:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import { ComponentTypes } from "../../models";
Why have these become double quotes? We should be using single quotes.

2022-05-16 08:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +  if (page.hasOwnProperty("group") & page.group) {
The first check adds nothing in this condition:
```suggestion
  if (page.group) {
```

2022-05-16 08:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +  if (page.hasOwnProperty("group") & page.group) {
Actually, should this _be_ `group` or should it be `groupId`, seeing as that's what you're using on line 21?

2022-05-16 08:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +    Object.entries(page.formData[page.groupId]).map(([key, value]) => {
Given what you're doing here, `forEach` makes more sense than `map`.

2022-05-16 08:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +    return [
No check that the `page` should be shown? It seems like there'd definitely be a situation within a group where you'd want pages to _not_ be shown.

2022-05-16 08:25 UTC, gardnersam requested changes

2022-05-16 08:25 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +          {row && row.group ? (
Is the check that row is defined here redundant given that `row.key` is accessed on the line above? I assume it would throw a 'trying to access key on undefined' sort of error there if row isn't defined.

2022-05-16 08:25 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
If the user hasn't answered an optional question I think this will show up as a blank line here. Possibly something to deal with in `getCYARowsForPage.js`

2022-05-16 08:25 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
>  };
Could you add test coverage for this new display option please? Ideally with inputs including multiple lines, some lines with blank ones inbetween etc

2022-05-16 08:25 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import { ComponentTypes } from "../../models";
should be single quotes

2022-05-16 08:25 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +  if (page.hasOwnProperty("group") & page.group) {
single quotes here as well

2022-05-16 08:25 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +      return answers.push(page.formData[key]);
possibly this is the place to handle empty answers?

2022-05-16 08:25 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +        group: true,
I'm not sure if this works if some answers on a CYA page are a group and some are not. Also wonder if this logic should be in `getCYARowsForContainer`

2022-05-18 08:17 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import { ComponentTypes } from "../../models";
Remove double quotes

2022-05-18 08:18 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
>  };
Added the test coverage

2022-05-18 08:18 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +import { ComponentTypes } from "../../models";
Remove double quotes

2022-05-18 08:19 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +      return answers.push(page.formData[key]);
Added the code to handle the empty answers

2022-05-18 08:34 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +    Object.entries(page.formData[page.groupId]).map(([key, value]) => {
Added foreach instead of map

2022-05-18 08:35 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.js
> +    return [
moved page inside if condition

2022-05-18 08:49 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +          formData: {addressDetails : [{
How is `addressDetails` an array? What type of component are you using to make this possible? As it stands, this looks like a JSON structure for `formData` that is impossible...

2022-05-18 08:54 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
I'm not sure this code has been updated

2022-05-18 08:54 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +        const PAGE = {
Should this test also cover having a blank line to check that works?

2022-05-18 08:54 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +          {row.group ? (
could this check the groupId prop instead so the group prop could be removed?

2022-05-18 08:54 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
You set value to '' if there is no value, will this cause problems if you try and make an array out of it?

2022-05-18 08:54 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +          expectObjectLike(ROWS[0], {
indentation slightly off here

2022-05-18 08:54 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +        const COMPONENT_ADDRESS = {id: 'firstLineOfTheAddress', fieldId: 'firstLineOfTheAddress', label: 'Address', type: 'text'};
are these still being used?

2022-05-18 09:13 UTC, paulfgraham commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
I don't think this should be an array. What type of component is producing a value that is an array right now?

`<Checkboxes />` and that's it, I think. This is clearly not for that component.

2022-05-18 10:05 UTC, Deepak-Bagrawat commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
`[
    {
        "pageId": "address-details",
        "groupId": "addressDetails",
        "fieldId": "UK address",
        "key": "UK address",
        "value": {
            "key": "8_0",
            "ref": null,
            "props": {
                "value": [
                    "10 Downing Street",
                    "London",
                    "City of Westminster",
                    "SW1A 2AA"
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "action": {
            "page": "address-details",
            "label": "Change",
            "aria_suffix": "address-details"
        },
        "group": true
    }
]`

2022-05-18 10:16 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +          formData: {addressDetails : [{
In your _test_ it is... but that's not possible. There is no component that currently exists in the Form Renderer or Component Library that will produce an array of objects like that. So, whilst the test might pass, and the code might behave itself with this data structure, it's not a real-world one. 🤷‍♂️

2022-05-20 08:20 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +        const COMPONENT_ADDRESS = {id: 'firstLineOfTheAddress', fieldId: 'firstLineOfTheAddress', label: 'Address', type: 'text'};
Testcase updated

2022-05-20 08:20 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +          expectObjectLike(ROWS[0], {
removed

2022-05-20 08:26 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +        const PAGE = {
Testcase updated

2022-05-20 09:06 UTC, Deepak-Bagrawat commented on src/components/SummaryList/SummaryList.jsx
> +              {Array.from(row.value.props.value).join('\r\n')}
code updated

2022-05-20 09:07 UTC, Deepak-Bagrawat commented on src/components/SummaryList/SummaryList.jsx
> +          {row.group ? (
code updated with new line of code

2022-05-20 09:16 UTC, gardnersam requested changes
Few code changes, we also need documentation for the new JSON structures this introduces so people can use the new features

2022-05-20 09:16 UTC, gardnersam commented on src/utils/CheckYourAnswers/getCYARowForGroup.js
> +      {group.components.map(componentId => {
if the component is optional and not filled what do we get here? I think maybe an empty line?

2022-05-20 09:24 UTC, Deepak-Bagrawat commented on src/components/SummaryList/SummaryList.jsx
> +      {rows.map((row) => (
yes, I have reverted my changes and now its same as it was earlier

2022-05-20 09:29 UTC, Deepak-Bagrawat commented on src/components/SummaryList/SummaryList.jsx
> +export default SummaryList;
Sorry, where do you want me to add new line? after line no 65 or 68?

2022-05-20 09:59 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +        expect(ROWS[0].value.props.children[0].props.children.props.value).toEqual(PAGE.formData.firstLineOfTheAddress);
Removed the duplicate.

2022-05-20 10:02 UTC, paulfgraham requested changes

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           name: 'address-details',
```suggestion
          name: 'address-details',
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           title: 'Address details',
```suggestion
          title: 'Address details',
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +            postCode: 'SW1A 2AA'},
```suggestion
            postCode: 'SW1A 2AA'
          },
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +
Extraneous blank line at the end here...

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           name: 'address-details',
```suggestion
          name: 'address-details',
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           title: 'Address details',
```suggestion
          title: 'Address details',
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +            postCode: 'SW1A 2AA'},
```suggestion
            postCode: 'SW1A 2AA'
          },
```

2022-05-20 10:02 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +
Two extraneous blank lines at the end.

2022-05-20 10:36 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +          groupLabel: 'UK address',
Removed redundant key value

2022-05-20 10:36 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           name: 'address-details',
Removed extra space

2022-05-20 10:36 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           title: 'Address details',
Removed extra space

2022-05-20 10:37 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +            postCode: 'SW1A 2AA'},
Code updated

2022-05-20 10:38 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +
Removed extra line

2022-05-20 10:38 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           name: 'address-details',
Removed extra space

2022-05-20 10:38 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +           title: 'Address details',
Removed extra space

2022-05-20 10:39 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +
Removed extra lines

2022-05-20 11:25 UTC, paulfgraham requested changes

2022-05-20 11:25 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowForGroup.js
> +import FormComponent from '../../components/FormComponent';
Actually, this will need to import `React` because it's outputting jsx...
```suggestion
import React from 'react';
import FormComponent from '../../components/FormComponent';
```

2022-05-20 11:31 UTC, gardnersam commented on src/components/SummaryList/SummaryList.jsx
> +      {rows.map((row) => (
it's still showing up as changed

2022-05-20 11:33 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +                 'firstLineOfTheAddress',
These 4 lines are all indented too far.

2022-05-20 11:33 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +                 'firstLineOfTheAddress',
Also indented too far...

2022-05-20 12:17 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +                 'firstLineOfTheAddress',
Fixed the indentation

2022-05-20 12:17 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowForGroup.js
> +import FormComponent from '../../components/FormComponent';
Added react import

2022-05-20 12:27 UTC, Deepak-Bagrawat commented on src/utils/CheckYourAnswers/getCYARowsForPage.test.js
> +                 'firstLineOfTheAddress',
Fixed the indentation

2022-05-24 10:14 UTC, gardnersam commented on src/components/CheckYourAnswers/CheckYourAnswers.test.js
> +    const DATA = Utils.Data.setupForm(GROUPED_ADDRESS.pages, GROUPED_ADDRESS.components, GROUPED_ADDRESS_DATA_JSON)
indentation is off here

2022-05-24 10:15 UTC, gardnersam commented on src/docs/Page.stories.mdx
> +The value for this object are `id, label and component` component is a array of string.
I'm not sure from this what Id, label and component should be, could each be explained?

2022-05-24 10:16 UTC, gardnersam commented on src/json/group.json
> +
don't need all these lines and github is complaining about a missing newline also..

2022-05-24 10:16 UTC, gardnersam commented on src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
> +      //const DATA = { firstName: 'John', surname: 'Smith', age: 41, team: 'London' };
should this commented out bit still be here

2022-05-24 11:27 UTC, Deepak-Bagrawat commented on src/components/CheckYourAnswers/CheckYourAnswers.test.js
> +    const DATA = Utils.Data.setupForm(GROUPED_ADDRESS.pages, GROUPED_ADDRESS.components, GROUPED_ADDRESS_DATA_JSON)
Indentation fixed

2022-05-24 11:28 UTC, Deepak-Bagrawat commented on src/docs/Page.stories.mdx
> +The value for this object are `id, label and component` component is a array of string.
Added more explanation with data

2022-05-24 11:29 UTC, Deepak-Bagrawat commented on src/json/group.json
> +
Removed lines

2022-05-24 11:30 UTC, Deepak-Bagrawat commented on src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
> +      //const DATA = { firstName: 'John', surname: 'Smith', age: 41, team: 'London' };
Removed

2022-05-24 14:17 UTC, gardnersam approved these changes
Looks good, thanks for the changes

2022-05-24 16:29 UTC, paulfgraham commented on src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
> +
Too many lines at the bottom here. There should only be one blank line.

2022-05-27 08:24 UTC, paulfgraham requested changes
Just a request to remove the hard-coded `rowsObj` in one of the tests. I've suggested a better solution.

2022-05-27 08:24 UTC, paulfgraham commented on src/utils/CheckYourAnswers/getCYARowForGroup.test.js
> +        const rowsObj = [
This is the hard-coded output from a series of calls to `getCYARow`, which is actually called within the `getCYARowsForPage`.

The problem here is that you're externalising an internal mechanism of that method and, by hard-coding it like this, you're making it much harder to maintain - if the output of `getCYARow` ever changes (entirely possible), you'll have to change this hard-coding to suit.

Instead, I suggest you call the method that `getCYARowsForPage` does and pass the output of that instead of this hard-coded value:
```
// Get a row object for each component on the page.
const rows = PAGE.components.map(component => {
  return getCYARow(PAGE, component, ON_ACTION);
});

// And then pass those rows to the method you're testing
const { container } = render(getCYARowForGroup(PAGE, PAGE.groups[0], rows, ON_ACTION).row.value);
```

2022-05-27 10:15 UTC, paulfgraham approved these changes

2022-05-27 10:18 UTC, merged