Feature/c op 2120 cya validation
UKHomeOffice/cop-react-form-renderer pull request #93
Opened 2022-05-18 13:37 UTC by georgepemberton1998

2022-05-18 14:14 UTC, paulfgraham requested changes
A few things I think could do with adjusting.

2022-05-18 14:14 UTC, paulfgraham commented on src/utils/Validate/validatePage.js
> +  if (Array.isArray(page?.components) && showFormPage(page, page.formData)) {
If you flip these conditions around, you won't need the optional chaining as a `null` or `undefined` page won't be shown:
```suggestion
  if (showFormPage(page, page.formData) && Array.isArray(page.components)) {
```

2022-05-18 14:14 UTC, paulfgraham commented on src/utils/Validate/validatePage.js
> +
Not sure why this extra blank line has been introduced...

2022-05-18 15:25 UTC, georgepemberton1998 commented on src/utils/Validate/validatePage.js
> +  if (Array.isArray(page?.components) && showFormPage(page, page.formData)) {
I made this change however the unit test now fails due to formData being null..

`  ● utils › Validate › page › should return no error when the components array is null

    TypeError: Cannot read properties of null (reading 'formData')

      11 |  */
      12 |  const validatePage = (page) => {
    > 13 |   if (showFormPage(page, page.formData) && Array.isArray(page.components)) {
         |                               ^
      14 |     return page.components.reduce((errors, component) => {
      15 |       return errors.concat(validateComponent(component, page.formData));
      16 |     }, []).filter(e => !!e).flat();

      at validatePage (src/utils/Validate/validatePage.js:13:31)
      at Object.<anonymous> (src/utils/Validate/validatePage.test.js:16:16)
`

I can avoid this by updated the first unit test to the following 
`      it('should return no error when the components array is null', () => {
        const PAGE = {
          components: null,
          formData: {
            alpha: 'alpha.smith@digital.homeoffice.gov.uk',
            bravo: 'bravo.jones@digital.homeoffice.gov.uk'
          }
        };
        expect(validatePage(PAGE).length).toEqual(0);
      });`
      
 Let me know if you would prefer that

2022-05-18 15:41 UTC, georgepemberton1998 commented on src/utils/Validate/validatePage.js
> +  if (Array.isArray(page?.components) && showFormPage(page, page.formData)) {
I have pushed a new commit addresses this and other comments - let me know if you would prefer to keep the optional chaining over editing the unit test and I can revert that part.

2022-05-19 08:07 UTC, paulfgraham approved these changes
Looks good, @georgepemberton1998. Thank you for making the requested changes. 👍

2022-05-19 08:09 UTC, merged